### ISSUE TITLE
Add (encode/decode)As5bits

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bech32#1]
Rather than inlining the address encoding/decoding into the same module,  I think it'd be better to put that elsewhere (eg `bitcoinjs-lib`).

Would still provide `bech32.encode/decode` for generic encoding/decoding.

**Comment by dcousens** [comment]
Desired API:

``` markdown
* encodeAs5Bits(prefix, words) -> string
* decodeAs5Bits(string) -> { prefix, words }
* to5BitWords
* from5BitWords
```

Thoughts?

**Comment by kabutosamourai** [comment]
Are these endpoints in addition to the existing `encode(prefix, bytes) -> string` and `decode(string) -> { prefix, bytes }`?

**Comment by dcousens** [comment]
@kabutosamourai the existing are `encode(prefix, words) -> string`,  and I don't think any other default makes sense,  maybe not even `encode(prefix, bytes)` as we have to make padding assumptions?

**Comment by dcousens** [comment]
I think maybe:
``` js
encode(prefix, words) -> string
decode(string) -> { prefix, words }
toWords(bytes, padding = false) -> words
fromWords(words, padding = false) -> bytes
```

I can't see any other conversion being useful,  at least,  not without an API revision being useful anyway?
