### ISSUE TITLE
Publish transpiled version of package

### ISSUE THREAD

**Issue by lapanoid** [bitcoinjs/bech32#13]
Hi, could you please transpile code before publishing? Otherwise old browsers that only supports es5 get's broken. 
Currently to workaround it, it should be transpiled by users of this lib.
```
{
          test: /\.jsx?$/,
          include: [path.resolve(__dirname, 'src'), /node_modules\/bech32/],
          use: 'babel-loader',
}
```

**Comment by dcousens** [comment]
> Otherwise old browsers that only supports es5 get's broken.

Browsers don't support common.js modules... so I wonder why you can't transpile when you transpile?

**Comment by lapanoid** [comment]
I don't transpile node_modules, only my src. Usually author of lib transpile before publishing, as consumer of library cannot support latest es features

**Comment by dcousens** [comment]
I don't understand,  we only support `node >=4.0.0`,  if you need ES5 for your browser,  you'll be transpiling somewhere,  probably bundling it up using `browserify` or `webpack`... if you need to guarantee ES5,  use a transform,   I can't guarantee you that even if it doesn't use `let`,  that it will work as expected in ES5.
