### ISSUE TITLE
Code fails to minify

### ISSUE THREAD

**Issue by elis** [bitcoinjs/bech32#14]
I'm using `create-react-app` to build an app and the build process is failing if `bech32` (e.g. `bitcoinjs-lib`) is part of dependencies.

Error from `npm run build`:

```
Failed to minify the code from this file:

 	./node_modules/bech32/index.js:1
```

I've tried to debug it but couldn't pinpoint the issue - one thing that I did confirm that if the index file in bech32 is empty from the original code the build process goes through without issues.

**Comment by dcousens** [comment]
Did you resolve this?

**Comment by fanatid** [comment]
webpack/browserify?

**Comment by dcousens** [comment]
Re-open if you can elaborate or provide steps to reproduce
