### ISSUE TITLE
Unsafe as in bs58?

### ISSUE THREAD

**Issue by fanatid** [bitcoinjs/bech32#23]
`base-x` have unsafe functions, which allow decode values without exceptions (return `undefined` on bad data)
https://github.com/cryptocoinjs/base-x/blob/v3.0.4/index.js#L51

Should we implement such functions here?

**Comment by dcousens** [comment]
@fanatid PR accepted :+1:

**Comment by fanatid** [comment]
@dcousens any ideas how this can be implemented except:
```js
function decodeUnsafe () {
  try {
    decode.apply(null, arguments)
  } catch (err) { return }
}
```

`decode`/`fromWords` have a lot of checks

base functions which will return error code + result and throwing error in `decode` by error code?

**Comment by dcousens** [comment]
> base function which will return error code + result and throw error in decode by error code?

That sounds sane.
`decodeUnsafe` should probably not return the error code though.
It is intentionally opaque.

**Comment by dcousens** [comment]
> fromWords have a lot of checks

That won't impact on `decodeUnsafe`,  unless you additionally want to add `fromWordsUnsafe`

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bech32/pull/24
