### ISSUE TITLE
How can I convert bech32 address to version 1 Bitcoin address ?

### ISSUE THREAD

**Issue by limpbrains** [bitcoinjs/bech32#25]
bench32.decode returns array of words. How can I use it to generate old bitcoin address ?

**Comment by afk11** [comment]
Check out the code for decoding a segwit address. You can decode it & use the public key hash as a P2PKH address. https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/address.js#L30

Just a heads up though, if you do this with other peoples addresses for a payment, they most likely won't receive it.

**Comment by random9brat** [comment]
I like this code but i need from p2pkh to bech32 (from public addresses which starts with 1 to pub addresses which starts with bc1)... If anyone knows the drill hit me, would appreciate a lot
