### ISSUE TITLE
Deleting or inserting characters produce valid strings 

### ISSUE THREAD

**Issue by ccorcoveanu** [bitcoinjs/bech32#34]
Regarding the recently documented issue where you basically can insert (or remove in some cases) `q` characters into a bech32 string and produce another valid bech32 string, are you guys planning on introducing the changes proposed Pieter Wuille?
The changes are really small and I would be more than happy to open a PR for this.

Background:
https://github.com/sipa/bech32/issues/51
https://gist.github.com/sipa/a9845b37c1b298a7301c33a04090b2eb

**Comment by junderw** [comment]
Pull Requests are welcome.

Personally I would like to wait until the fixes are nailed down in a BIP. But I will definitely review the PR while we wait.

**Comment by ccorcoveanu** [comment]
Cool, I will open the PR this week, thanks! :)

**Comment by junderw** [comment]
Fixed in #40
