### ISSUE TITLE
package.json does not reference index.d.ts

### ISSUE THREAD

**Issue by camilbancioiu** [bitcoinjs/bech32#35]
Running `npm install --save bitcoinjs/bech32` does not download the `index.d.ts` file, required for TypeScript. The current `package.json` contains this:
```
"files": [
    "index.js"
  ],
```
Should it rather contain this, instead?
```
"files": [
    "index.js",
    "index.d.ts"
  ],
```

**Comment by junderw** [comment]
Thanks for the catch! I published a new patch with a fix. #36

**Comment by camilbancioiu** [comment]
Ah, already! Many thanks.
