### ISSUE TITLE
P2PKH to bech32

### ISSUE THREAD

**Issue by random9brat** [bitcoinjs/bech32#46]
Sry if this is a dumb questions. But as title says.

I have for example 1LKp8CTu2b4VDvybY9iMn3DoV1cm6ZLsrR address created from bitcoinjs-lib/coinjs-lib/bip39 and i want to convert it to bech32?

How can i do it? Thanks for the responses in advance <3

**Comment by junderw** [comment]
This is irrelevant to a library whose sole purpose is to encode and decode bech32 text.

You already have an issue on a relevant repository.
