### ISSUE TITLE
How to get a Taproot address from ScriptPubKey I got?

### ISSUE THREAD

**Issue by Overtorment** [bitcoinjs/bech32#48]
Examples & tests are not very verbose, and I could not figure it out on my own.

Hex i got: `658204033e46a1fa8cceb84013cfe2d376ca72d5f595319497b95b08aa64a970`

Address Im hoping to get: `bc1pvkpqgqe7g6sl4rxwhpqp8nlz6dmv5uk47k2nr9yhh9ds32ny49cqdcghmx`

For reference: https://mempool.space/tx/37d5ec4bca7bd077992a6dd8679ab676a22986e63ebaf2c6ea1aebe5e5f5e817

**Comment by junderw** [comment]
```js
function pubkeyToP2TR(pubkey) {
    console.log(bitcoinJsLib.payments.p2tr({ pubkey }).address)
}

pubkeyToP2TR(Buffer.from('658204033e46a1fa8cceb84013cfe2d376ca72d5f595319497b95b08aa64a970', 'hex'))
```

Your example is an invalid pubkey, so it's an unspendable blackhole.

**Comment by junderw** [comment]
https://mempool.space/tx/c8b8e8ccb2844997c04ba173e24c7a34e6bdf0fa4d5074f5d094a9cc6ae34212

Checking this tx, looking at details, you'll see `5eaa2d0c0c79b6bd015a49b1f63dfeb0ace807846e417f8d1fd849f7b04528c7`

If you put that into my code above you'll get the address.

**Comment by Overtorment** [comment]
then how did mempoolspace derive this address from this specific invalid pubkey?
https://mempool.space/tx/37d5ec4bca7bd077992a6dd8679ab676a22986e63ebaf2c6ea1aebe5e5f5e817
i did try `payments.p2tr({ pubkey }).` and indeed notice that it throws invalid public key error.


for my use case i need to derive it anyway as i am working on a chainsate parser and this is what i see in bitcoind chainstate and this is what i need to show to the user.

**Comment by Overtorment** [comment]
also, i found this lib that renders the same address as mempoolspace and blockstreaminfo:


```js
    const bech32 = require('bech32-buffer');
    const { BitcoinAddress } = bech32;
    const script = Buffer('5120658204033e46a1fa8cceb84013cfe2d376ca72d5f595319497b95b08aa64a970', 'hex');
    const add = new BitcoinAddress('bc', 1, script.slice(2));
    const address = add.encode();
    console.log(address);
```


```
  console.log
    bc1pvkpqgqe7g6sl4rxwhpqp8nlz6dmv5uk47k2nr9yhh9ds32ny49cqdcghmx
```

**Comment by junderw** [comment]
Pass `{ validate: false }` as an option. By doing this you don't check the point, so you don't even need to run `initEccLib` on the library.

Be careful, though. validate = false means it won't check anything at all, and assumes you are sure your input is correct.

```js
function pubkeyToP2TR(pubkey) {
    console.log(bitcoinJsLib.payments.p2tr({ pubkey }, { validate: false }).address)
}

pubkeyToP2TR(Buffer.from('658204033e46a1fa8cceb84013cfe2d376ca72d5f595319497b95b08aa64a970', 'hex'))
// Will print bc1pvkpqgqe7g6sl4rxwhpqp8nlz6dmv5uk47k2nr9yhh9ds32ny49cqdcghmx
```
