### ISSUE TITLE
Permits invalid checksums

### ISSUE THREAD

**Issue by afk11** [bitcoinjs/bech32#7]
https://github.com/bitcoinjs/bech32/blob/master/bech32.js#L116 this allows the wrong checksum half the time.

To be honest it might be worth reverting to sipa's implementation, or following it's API at least. I really think It's more readable instead of having about 2 or 3 different processes happening in bech32.js decode/encode

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bech32/pull/9
